#!/bin/bash
###############################################################################
#                                                                             #
#  Copyright (C) 2024-2026  RPZ Team                                          #
#                                                                             #
#  This program is free software: you can redistribute it and/or modify       #
#  it under the terms of the GNU General Public License as published by       #
#  the Free Software Foundation, either version 3 of the License, or          #
#  (at your option) any later version.                                        #
#                                                                             #
#  This program is distributed in the hope that it will be useful,            #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of             #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              #
#  GNU General Public License for more details.                               #
#                                                                             #
#  You should have received a copy of the GNU General Public License          #
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.      #
#                                                                             #
###############################################################################

versions="2026-02-18 - v15"

###############     Functions     ###############

source "/usr/sbin/rpz-functions"

#   create the RPZ config file for either "allow" or "block"
make_rpz_config () {
    local theName="${1-block}"
    local theLog="${2:-yes}"                            #  log default ON

    local theRPZfile="/etc/unbound/zonefiles/${theName}.rpz"
    local theList="/var/ipfire/dns/rpz/${theName}list"

    #  type-specific values
    local theConfFile theAction
    case "${theName}" in
        allow)
            theConfFile="/etc/unbound/local.d/00-rpz.conf"
            theAction="passthru"
            ;;
        block)
            theConfFile="/etc/unbound/local.d/block.rpz.conf"
            theAction="nxdomain"
            ;;
        *)
            msg_log "error: make_rpz_config: unknown type '${theName}'" >&2
            return 1
            ;;
    esac

    msg_log "info: rpz: make config file '$(basename "${theConfFile}")'"

	: > "${theConfFile}"
    #  allow needs a server: header written
    if [[ "${theName}" == "allow" ]]; then
        echo "server:
    module-config: \"respip validator iterator\"" > "${theConfFile}"
    fi

    #  does the list exist and contain at least one entry?
    if [[ -s "${theList}" ]] && grep -q . "${theList}"; then

        echo "rpz:
    name:                   ${theName}
    zonefile:               ${theRPZfile}
    rpz-action-override:    ${theAction}
    rpz-log:                ${theLog}
    rpz-log-name:           ${theName}
    rpz-signal-nxdomain-ra: yes" >> "${theConfFile}"

        set_permissions "${theConfFile}"

    elif [[ "${theName}" == "block" ]]; then
        #  no block list – remove the stale config so unbound won't error
        rm --verbose "${theConfFile}"
    fi
}

#   create an RPZ file for allow or block
make_rpz_file () {
    local theName="${1}"        #   allow or block
    local theAction='.'         # the default is nxdomain (a.k.a block)
    local actionList

    local theList="/var/ipfire/dns/rpz/${theName}list"         #  input custom list of domains
    local theZonefile="/etc/unbound/zonefiles/${theName}.rpz"  #  output file for RPZ

    #  does a list exist?
    if [[ -s "${theList}" ]] && grep -q . "${theList}" ; then

        # for allow set to passthru
        [[ "${theName}" == allow ]] && theAction='rpz-passthru.'

        #  drop any extra "blanks" and add "CNAME <RPZ action>." to each line
        actionList=$( awk '{$1=$1};1' "${theList}" |
            sed "/^[^;].*[[:alnum:]]/ s|$|	CNAME	${theAction}|" )

        msg_log "info: rpz: create zonefile for '${theName}list'"

echo "; Name:             ${theName} list
; Last modified:    $(date "+%Y-%m-%d at %H.%M.%S %Z")
;
;   domains with actions list
;
${actionList}" > "${theZonefile}"

        #  set-up zonefile - unbound requires these settings for rpz files
        set_permissions "${theZonefile}"
        #  set-up allow/block list files
        set_permissions "${theList}"
    else
        msg_log "info: rpz: the ${theList} is empty."

        rm --verbose "${theZonefile}"   # trash the RPZ file
    fi
}

#   check if allow/block list is valid
validate_list () {
    local theName="${1}"        #   allow or block
    local theList="/var/ipfire/dns/rpz/${theName}list"  #  input custom list of domains

	#   remove good:
	#    - properly formated domain names with or without leading wildcard
	#    - properly formated top level domain (TLD) names with wildcard
	#    - blank lines and comment lines
	#   remaining lines are considered "bad"
    bad_lines=$( sed --regexp-extended  \
        '/^(\*\.)?([a-zA-Z0-9](([a-zA-Z0-9\-]){0,61}[a-zA-Z0-9])?\.)+([a-zA-Z]{2,}|xn--[a-zA-Z0-9][a-zA-Z0-9\-]*[a-zA-Z0-9])$/d ;
         /^(\*\.)([a-z]{2,61}|xn--[a-z0-9]{1,60})$/d ;
         /^$/d ; /^;/d' "${theList}" )

    if [[ ! -z "${bad_lines}" ]] ; then
        msg_log "error: rpz: invalid line(s) in ${theList}."
        printf "%s\n" "bad line(s): ${bad_lines}"
        exit 110
    fi
}


###############       Main        ###############

tagName="unbound"

rpzName="${1}"                      #  input RPZ name

rpzLog="yes"                        #  log default is yes
ucReload="yes"                      #  reload default is yes

while [[ $# -gt 0 ]] ; do
    case "$1" in
        --no-log )      rpzLog="no"   ;;
        --no-reload )   ucReload="no" ;  checkConf="no" ;;
    esac
    shift       # Shift after checking all the cases to get next option
done

case "${rpzName}" in
    #  make a new allow or block rpz file

    allow )
        validate_list 'allow'           #  is the allow list valid?
        make_rpz_config 'allow' "${rpzLog}"
        make_rpz_file 'allow'
        ;;

    allowblock )
        validate_list 'allow'           #  is the allow list valid?
        make_rpz_config 'allow' "${rpzLog}"
        make_rpz_file 'allow'
        ;&								#  drop thru to next

    block )
        validate_list 'block'           #  is the blocklist valid?
        make_rpz_config 'block' "${rpzLog}"
        make_rpz_file 'block'
        ;;

    reload )
        check_unbound_conf "${checkConf}"
        ;;

    unbound-restart )
        check_unbound_conf "${checkConf}"
		unbound_restart
		exit
        ;;

    * )
        msg_log "error: rpz: missing or incorrect parameter"
        printf "Usage:   $(basename "$0") <NAME> <OPTION> <OPTION>\n"
        printf "Version: ${versions}\n"
        exit 108
        ;;
esac

unbound_control_reload "${ucReload}"

exit
