#!/bin/bash
set -o errexit -o nounset -o pipefail

###############################################################################
#                                                                             #
#  Copyright (C) 2024-2026  RPZ Team                                          #
#                                                                             #
#  This program is free software: you can redistribute it and/or modify       #
#  it under the terms of the GNU General Public License as published by       #
#  the Free Software Foundation, either version 3 of the License, or          #
#  (at your option) any later version.                                        #
#                                                                             #
#  This program is distributed in the hope that it will be useful,            #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of             #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              #
#  GNU General Public License for more details.                               #
#                                                                             #
#  You should have received a copy of the GNU General Public License          #
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.      #
#                                                                             #
###############################################################################

version="2026-02-18 - v31"

##############################     Functions     ##############################
# Extract hit count for RPZ zone from pre-computed "name count" list
get_rpz_hits() {
    local name=$1
    local rpzNameCount=$2
    grep "^${name}\s" <<< "${rpzNameCount}" | awk '{print $2}' || echo "0"
}

# Extract CNAME line count for RPZ zone from pre-computed file:count list
get_rpz_lines() {
    local name=$1
    local cnameCount=$2
	grep --fixed-strings "/${name}.rpz:" <<< "${cnameCount}" | awk -F: '{print $2}' || echo "n/a"
}

# Extract last modified date for RPZ zone from pre-computed "date file" list
get_rpz_moddate() {
    local name=$1
    local modDateList=$2
    grep "/${name}.rpz$" <<< "${modDateList}" | awk '{ print $1 }' || echo "n/a"
}

# Check if RPZ zone is active (loaded + non-empty)
is_rpz_list_active() {
    local name=$1
    local ucListAuthZones=$2
    local cnameCount=$3
	# Require it in list_auth_zones and have non-zero CNAME count
    grep -E --quiet "^${theName}(\.rpz\.|\.)?\s" <<< "${ucListAuthZones}" && \
        ! grep --quiet "/${name}\.rpz:0$" <<< "${cnameCount}"
}

################################     Main     ################################

weeks="4"                   #   default to two message logs
sortBy="name"               #   default "by name"
rpzActive="enabled"         #   default "enabled only"

while [[ $# -gt 0 ]] ; do
    case "$1" in
        --by-names | --by-name | name )				sortBy="name"		;;

        --by-hits | --by-hit | hits | hit )     	sortBy="hit"		;;

        --by-lines | --by-line | lines | line )    	sortBy="line"		;;

        --enabled-only )            				rpzActive="enabled" ;;

        --active-all | --all | all )      			rpzActive="all"     ;;

        [0-9] | [0-9][0-9] )        				weeks=$1			;;

        *)	echo "Unknown option: $1" >&2 ; exit 1						;;

    esac
    shift       # Shift after checking all the cases to get next option
done

#  get the list of message logs for N weeks
readarray -t messageLogs < <(
    find /var/log -maxdepth 1 -name 'messages*' -type f |
    sort --version-sort |
    head -"${weeks}")

#  get the list of RPZ names & counts from the message log(s)
rpzNameCount=$(
  printf '%s\0' "${messageLogs[@]}" |
  xargs -0 zgrep --text --fixed-strings 'info: rpz: applied' |
  awk '$10 ~ /\[[a-zA-Z0-9.-]*\]/ { print $10 }'|
    sort |
    uniq --count)

#  flip results and remove brackets [ and ]
rpzNameCount=$(
	echo "${rpzNameCount}" |
    awk '{ print $2, $1 }' |
    sed --regexp-extended 's|^\[(.*)\]|\1|' )

#  get list of RPZ files in /etc/unbound directory
readarray -t rpzFileList < <(
	find /etc/unbound/zonefiles -type f \( -iname "*.rpz" -o -iname "*.zone" \) )

#  get basename of those files
rpzBaseNames=$(
    printf '%s\n' "${rpzFileList[@]}" |
    sed 's|/etc/unbound/zonefiles/||g ; s|\.rpz$||g ; s|\.zone$||g ;' )

#  grab only names
rpzNames=$( echo "${rpzNameCount}" | awk '{ print $1 }' )

#  add to rpzNames and drop duplicate names
rpzNames=$( echo "${rpzNames}"$'\n'"${rpzBaseNames}" | sort --unique )

#  get CNAME count for each RPZ list
cnameCount=$( grep --count --fixed-strings ' CNAME ' -- "${rpzFileList[@]}" )

#  get modified date each RPZ
modDateList=$( stat -c '%.10y  %n' -- "${rpzFileList[@]}" )

ucListAuthZones=$( unbound-control list_auth_zones )

#  widths of every column
cName=$( echo "${rpzNames}" | awk '{ print $1" " }' | wc -L )
cHits=10  ; cActive=12 ; cLines=10 ; cDate=14

pFormat="%-${cName}s %${cHits}s %${cActive}s %${cLines}s %${cDate}s\n"

#  print title line and dash line
printf "${pFormat}" "name" "hits" "active" "lines" "last download"
totalWidth=$((cName + cHits + cActive + cLines + cDate + 5))
printf "%${totalWidth}s\n" | tr ' ' '-'

theResults=""
totalLines=0
totalHits=0

while read -r theName ; do
	#  is this RPZ list active?
    if is_rpz_list_active "${theName}" "${ucListAuthZones}" "${cnameCount}"; then
        theActive="enabled"
    else
        theActive="disabled"
		# 	When rpzActive=all: include disabled zones + their hit counts in totals
        [[ "${rpzActive}" == enabled ]] && continue
    fi

	#  get hit count for the RPZ name.  Only reaches here if: enabled OR rpzActive=all
	theHits=$(get_rpz_hits "${theName}" "${rpzNameCount}")

    #  get line count for the RPZ name
	theLines=$(get_rpz_lines "${theName}" "${cnameCount}")

    #  get modification date for the RPZ name
    theModDate=$(get_rpz_moddate "${theName}" "${modDateList}")

	#  total it up
	totalHits=$(( totalHits + theHits ))
	[[ "${theLines}" != "n/a" ]] && totalLines=$(( totalLines + theLines ))

    #  add to results list
    theResults+="${theName} ${theHits} ${theActive} ${theLines} ${theModDate}"$'\n'
done <<< "${rpzNames}"

case "${sortBy}" in
    #  sort by "active" then by "name"
    name) sortArg=("-k3,3r" "-k1,1")				;;

    #  sort by "active" then by "hits" then by "name"
    hit)  sortArg=("-k3,3r" "-k2,2nr" "-k1,1")		;;

    #  sort by "active" then by "lines" then by "name"
    line) sortArg=("-k3,3r" "-k4,4nr" "-k1,1")		;;

    #  sort by "active" then by "effect" then by "name"
    effect) sortArg=("-k3,3r" "-k5,5nr" "-k1,1")	;;

	# default to name
	*) sortArg=("-k3,3r" "-k1,1") ;;
esac

# Sort and print the results
echo "${theResults}" |
    awk '!/^[[:space:]]*$/' |
    sort "${sortArg[@]}"	|
    awk -v cN1="${cName}" -v cH2="${cHits}" -v cA3="${cActive}" -v cL4="${cLines}" -v cD5="${cDate}" \
        '{ printf "%-*s %*s %*s %*s %*s\n", cN1, $1, cH2, $2, cA3, $3, cL4, $4, cD5, $5 }'

printf "%-${cName}s %${cHits}s %$((cActive + cLines +1))s\n" "" "=========" "========="
printf "%-${cName}s %'${cHits}d %'$((cActive + cLines + 1))d\n" "Totals -->" "${totalHits}" "${totalLines}"

exit
