#!/bin/bash
###############################################################################
#                                                                             #
#  IPFire.org - A linux based firewall                                        #
#  Copyright (C) 2024  IPFire Team  <info@ipfire.org>                         #
#                                                                             #
#  This program is free software: you can redistribute it and/or modify       #
#  it under the terms of the GNU General Public License as published by       #
#  the Free Software Foundation, either version 3 of the License, or          #
#  (at your option) any later version.                                        #
#                                                                             #
#  This program is distributed in the hope that it will be useful,            #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of             #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              #
#  GNU General Public License for more details.                               #
#                                                                             #
#  You should have received a copy of the GNU General Public License          #
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.      #
#                                                                             #
###############################################################################

#	v23 - 2024-07-30

###############     Functions     ###############

msg_log () {
	/usr/bin/logger --tag "${tagName}" "$*"
	if tty --silent ; then
		echo "${tagName}:" "$*"
	fi
}

check_name () {
	local testName="${1}"
	#	check for a valid name
	regex='^[a-zA-Z0-9_]+$'
	if [[ ! "${testName}" =~ $regex ]] ; then
		msg_log "error: rpz: the NAME is not valid: \"${testName}\". exit."
		exit 1
	fi
}

check_unbound_conf () {
	#	check the above config files
	msg_log "info: rpz: check for errors with \"unbound-checkconf\""
	/usr/sbin/unbound-checkconf
	exit_code=$?
	if [[ "${exit_code}" -ne 0 ]] ; then
		msg_log "error: rpz: unbound-checkconf. exit."
		exit "${exit_code}"
	fi
}

make_rpz_file () {
	local theType="${1}"	#	allow or block

	theList="/var/ipfire/dns/rpz/${theType}list"				#	input user list of domains
	theZoneFile="/etc/unbound/zonefiles/${theType}.rpz"		#	output file for RPZ

	theAction='.'
	if [[ "${theType}" =~ "allow" ]] ; then
		theAction='rpz-passthru.'
	fi

	#	does a list exist?
	if [[ -s "${theList}" ]] ; then
		#	drop any extra "blanks" and add "CNAME <RPZ action>." to each line
		actionList=$( /usr/bin/awk '{$1=$1};1' "${theList}" |
			/bin/sed "/^[^;].*[[:alnum:]]/ s|$|	CNAME	${theAction}|" )

		msg_log "info: rpz: create zonefile for ${theList}"

		/bin/cat <<-EOF > "${theZoneFile}"
		; Name:				${theType} list
		; Last modified:	$(date "+%Y-%m-%d at %H.%M.%S %Z")
		;
		;	domains with actions list
		;
		${actionList}
		EOF

		#	reload the zone that was just updated
		zoneBase=$( basename "${theZoneFile}" )
		/usr/sbin/unbound-control auth_zone_reload -q "${zoneBase}"
	fi
}

###############       Main        ###############

tagName="unbound"

theAction="${1}"										#	input action
theName="${2}"											#	input RPZ name
theURL="${3}"											#	input RPZ URL

check_name "${theName}"									#	is this a valid name?

rpzConfig="/etc/unbound/local.d/${theName}.rpz.conf"	#	output zone conf file
rpzFile="/etc/unbound/zonefiles/${theName}.rpz"			#	output for RPZ file

case "${theAction}" in

	#	add new rpz list
	add )
		#	does this config already exist?  If yes, then exit
		if [[ -f "${rpzConfig}" ]] ; then
			msg_log "info: rpz: ${rpzConfig} already exists. exit"
			exit 1
		fi

		#	is this a valid URL?
		regex='^https://[-[:alnum:]\+&@#/%?=~_|!:,.;]*[-[:alnum:]\+&@#/%=~_|]'
		if ! [[ "${theURL}" =~ $regex ]] ; then
			msg_log "error: rpz: the URL is not valid: \"${theURL}\". exit."
			exit 1
		fi

		#	create the zone config file
		msg_log "info: rpz: add config file \"${theName}.rpz.conf\""
		cat <<-EOF > "${rpzConfig}"
		rpz:
			name:					${theName}.rpz
			zonefile:				/etc/unbound/zonefiles/${theName}.rpz
			url:  ${theURL}
			rpz-action-override:	nxdomain
			rpz-log:				yes
			rpz-log-name:			${theName}
			rpz-signal-nxdomain-ra:	yes
		EOF

		#	set-up zone file
		/usr/bin/touch "${rpzFile}"
		#	unbound requires these settings for rpz files
		/bin/chown nobody:nobody "${rpzFile}"
		/bin/chmod 644 "${rpzFile}"
		;;

	#	trash config file & rpz file
	remove )
		if ! [[ -f "${rpzConfig}" ]] ; then
			msg_log "info: rpz: ${rpzConfig} does not exist. exit"
			exit 1
		fi

		msg_log "info: rpz: remove config file & rpz file \"${theName}\""
		/bin/rm "${rpzConfig}"
		/bin/rm "${rpzFile}"

		check_unbound_conf
		;;

	#	make a new allow or block rpz file
	make )
		case "${theName}" in
			allow )
				make_rpz_file allow
			;;

			block )
				make_rpz_file block
			;;

			allowblock )
				make_rpz_file allow
				make_rpz_file block
			;;

			* )
				msg_log "error: rpz: the NAME is not valid: \"${theName}\". exit."
				exit 1
			;;
		esac

		check_unbound_conf
		;;

	*)
		msg_log "error: rpz: missing or incorrect parameter"
		/usr/bin/printf "Usage:  rpzConfig.sh <ACTION> <NAME> <URL>\n"
		exit 1
		;;

esac

#	reload due to the changes
msg_log  "rpz: running \"unbound-control reload\""
/usr/sbin/unbound-control reload
exit_code=$?
if [[ "${exit_code}" -ne 0 ]] ; then
	msg_log "error: rpz: unbound-control \"${theName}\". exit."
	exit "${exit_code}"
fi

exit
