#!/bin/bash
###############################################################################
#                                                                             #
#  IPFire.org - A linux based firewall                                        #
#  Copyright (C) 2024  IPFire Team  <info@ipfire.org>                         #
#                                                                             #
#  This program is free software: you can redistribute it and/or modify       #
#  it under the terms of the GNU General Public License as published by       #
#  the Free Software Foundation, either version 3 of the License, or          #
#  (at your option) any later version.                                        #
#                                                                             #
#  This program is distributed in the hope that it will be useful,            #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of             #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              #
#  GNU General Public License for more details.                               #
#                                                                             #
#  You should have received a copy of the GNU General Public License          #
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.      #
#                                                                             #
###############################################################################

version="2024-08-16"	# v27

###############     Functions     ###############

msg_log () {
    logger --tag "${tagName}" "$*"
    if tty --silent ; then
        echo "${tagName}:" "$*"
    fi
}

check_name () {
    local testName="${1}"
    #  check for a valid name
    regex='^[a-zA-Z0-9_]+$'
    if [[ ! "${testName}" =~ $regex ]] ; then
        msg_log "error: rpz: the NAME is not valid: \"${testName}\". exit."
        exit 101
    fi
}

check_unbound_conf () {
    #  check the above config files
    msg_log "info: rpz: check for errors with \"unbound-checkconf\""
    unbound-checkconf
    exit_code=$?
    if [[ "${exit_code}" -ne 0 ]] ; then
        msg_log "error: rpz: unbound-checkconf found invalid configuration."
        msg_log "error: rpz: In the Terminal run the command \
          \"unbound-checkconf\" for more information. exit."
        exit 102
    fi
}

make_rpz_file () {
    local theType="${1}"    #   allow or block

    theList="/var/ipfire/dns/rpz/${theType}list"         #  input custom list of domains
    theZoneFile="/etc/unbound/zonefiles/${theType}.rpz"  #  output file for RPZ

    #  does a list exist?
    if ! [[ -s "${theList}" ]] ; then
        msg_log "error: rpz: the ${theList} is empty. exit."
        exit 103
    fi

    theAction='.'
    if [[ "${theType}" =~ "allow" ]] ; then
        theAction='rpz-passthru.'
    fi

    #  drop any extra "blanks" and add "CNAME <RPZ action>." to each line
    actionList=$( awk '{$1=$1};1' "${theList}" |
        sed "/^[^;].*[[:alnum:]]/ s|$|  CNAME   ${theAction}|" )

    msg_log "info: rpz: create zonefile for ${theList}"

echo "
; Name:             ${theType} list
; Last modified:    $(date "+%Y-%m-%d at %H.%M.%S %Z")
;
;   domains with actions list
;
${actionList}
" > "${theZoneFile}"

}

###############       Main        ###############

tagName="unbound"

theAction="${1}"                    #  input action
theName="${2}"                      #  input RPZ name
theURL="${3}"                       #  input RPZ URL

check_name "${theName}"             #  is this a valid name?

rpzConfig="/etc/unbound/local.d/${theName}.rpz.conf"    #  output zone conf file
rpzFile="/etc/unbound/zonefiles/${theName}.rpz"         #  output for RPZ file

case "${theAction}" in

    #  add new rpz list
    add )
        #  does this config already exist?  If yes, then exit
        if [[ -f "${rpzConfig}" ]] ; then
            msg_log "error: rpz: duplicate - ${rpzConfig} already exists. exit"
            exit 104
        fi

        #  is this a valid URL?
        regex='^https://[-[:alnum:]\+&@#/%?=~_|!:,.;]*[-[:alnum:]\+&@#/%=~_|]'
        if ! [[ "${theURL}" =~ $regex ]] ; then
            msg_log "error: rpz: the URL is not valid: \"${theURL}\". exit."
            exit 105
        fi

        #  create the zone config file
        msg_log "info: rpz: add config file \"${theName}.rpz.conf\""
echo "rpz:
    name:                   ${theName}.rpz
    zonefile:               /etc/unbound/zonefiles/${theName}.rpz
    url:                    ${theURL}
    rpz-action-override:    nxdomain
    rpz-log:                yes
    rpz-log-name:           ${theName}
    rpz-signal-nxdomain-ra: yes
" > "${rpzConfig}"
        
        #  set-up zonefile
        #    create an empty rpz file
        touch "${rpzFile}"
        #  unbound requires these settings for rpz files
        chown nobody:nobody "${rpzFile}" "${rpzConfig}"
        chmod 644 "${rpzFile}" "${rpzConfig}"
        ;;

    #  trash config file & rpz file
    remove )
        if ! [[ -f "${rpzConfig}" ]] ; then
            msg_log "error: rpz: cannot remove ${rpzConfig}, does not exist. exit"
            exit 106
        fi

        msg_log "info: rpz: remove config file & rpz file \"${theName}\""
        rm "${rpzConfig}"
        rm "${rpzFile}"

        check_unbound_conf
        ;;

    #  make a new allow or block rpz file
    make )
        case "${theName}" in
            allow )
            make_rpz_file allow
            ;;

        block )
            make_rpz_file block
            ;;

        allowblock )
            make_rpz_file allow
            make_rpz_file block
            ;;

        * )
            msg_log "error: rpz: the NAME \"${theName}\" \
              is not valid - \"allow\" or \"block\" only.  exit."
            exit 107
            ;;
        esac

        check_unbound_conf
        ;;

    *)
        msg_log "error: rpz: missing or incorrect parameter"
        printf "Usage:  rpzConfig <ACTION> <NAME> <URL>\n"
        printf "Version:  ${version}\n"
        exit 108
        ;;

esac

#  reload due to the changes
msg_log  "rpz: running \"unbound-control reload\""
unbound-control reload
exit_code=$?
if [[ "${exit_code}" -ne 0 ]] ; then
    msg_log "error: rpz: unbound-control \"${theName}\". exit."
    exit 109
fi

printf "${theName}=${theURL}\n"

exit
