#!/bin/bash
###############################################################################
#                                                                             #
#  IPFire.org - A linux based firewall                                        #
#  Copyright (C) 2024  IPFire Team  <info@ipfire.org>                         #
#                                                                             #
#  This program is free software: you can redistribute it and/or modify       #
#  it under the terms of the GNU General Public License as published by       #
#  the Free Software Foundation, either version 3 of the License, or          #
#  (at your option) any later version.                                        #
#                                                                             #
#  This program is distributed in the hope that it will be useful,            #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of             #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              #
#  GNU General Public License for more details.                               #
#                                                                             #
#  You should have received a copy of the GNU General Public License          #
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.      #
#                                                                             #
###############################################################################

version="2024-09-03   v02"


###############     Functions     ###############

source /usr/sbin/rpz-functions

#	create the config file for allow
make_allow_config () {
	local theLog="${1:-yes}"
	local theConfig="/etc/unbound/local.d/00-rpz.conf"    #  output zone conf file

    msg_log "info: rpz: make config file \"00-rpz.conf\""

echo "server:
    module-config: \"respip validator iterator\"

rpz:
    name:                   allow.rpz
    zonefile:               /etc/unbound/zonefiles/allow.rpz
    rpz-action-override:    passthru
    rpz-log:                ${theLog}
    rpz-log-name:           allow
    rpz-signal-nxdomain-ra: yes" > "${theConfig}"

	#  set-up zonefile - unbound requires these settings for rpz files
	set_permissions "${theConfig}"
}

#	create the config file for block
make_block_config () {
	local theLog="${1:-yes}"
	local theConfig="/etc/unbound/local.d/block.rpz.conf"    #  output zone conf file

    msg_log "info: rpz: make config file \"block.rpz.conf\""

echo "rpz:
    name:                   block.rpz
    zonefile:               /etc/unbound/zonefiles/block.rpz
    rpz-action-override:    nxdomain
    rpz-log:                ${theLog}
    rpz-log-name:           block
    rpz-signal-nxdomain-ra: yes" > "${theConfig}"

	#  set-up zonefile - unbound requires these settings for rpz files
	set_permissions "${theConfig}"
}

#	create an RPZ file for allow or block
make_rpz_file () {
    local theName="${1}"    	#   allow or block
    local theAction='.'         # the default is nxdomain or block

    local theList="/var/ipfire/dns/rpz/${theName}list"         #  input custom list of domains
    local theZonefile="/etc/unbound/zonefiles/${theName}.rpz"  #  output file for RPZ

    #  does a list exist?
    if ! [[ -s "${theList}" ]] ; then
        msg_log "error: rpz: the ${theList} is empty. exit."
        exit 103
    fi

    [[ "${theName}" == allow ]] && theAction='rpz-passthru.'	# for allow set to passthru

    #  drop any extra "blanks" and add "CNAME <RPZ action>." to each line
    actionList=$( awk '{$1=$1};1' "${theList}" |
        sed "/^[^;].*[[:alnum:]]/ s|$|  CNAME   ${theAction}|" )

    msg_log "info: rpz: create zonefile for \"${theName}list\""

echo "; Name:             ${theName} list
; Last modified:    $(date "+%Y-%m-%d at %H.%M.%S %Z")
;
;   domains with actions list
;
${actionList}" > "${theZonefile}"

	#  set-up zonefile - unbound requires these settings for rpz files
 	set_permissions "${theZonefile}"
}


###############       Main        ###############

tagName="unbound"

rpzName="${1}"                      					#  input RPZ name

rpzConfig="/etc/unbound/local.d/${rpzName}.rpz.conf"    #  output zone conf file
rpzFile="/etc/unbound/zonefiles/${rpzName}.rpz"         #  output for RPZ file

rpzLog="yes"                        #  log default is yes
ucReload="yes"						#  reload default is yes

while [[ $# -gt 0 ]] ; do
    case "$1" in
        --no-log )		rpzLog="no"   ;;
        --no-reload )	ucReload="no" ; checkConf="no" ;;
    esac
    shift		# Shift after checking all the cases to get next option
done

case "${rpzName}" in

    #  make a new allow or block rpz file
	allow )
		make_allow_config "${rpzLog}"
		make_rpz_file allow
		;;

	allowblock )
		make_allow_config "${rpzLog}"
		make_rpz_file allow
		;&

	block )
		make_block_config "${rpzLog}"
		make_rpz_file block
		;;

	reload )
		check_unbound_conf "${checkConf}"
		;;

	* )
        msg_log "error: rpz: missing or incorrect parameter"
        printf "Usage:   $(basename "$0") <NAME> <OPTION> <OPTION>\n"
        printf "Version: ${version}\n"
        exit 108
        ;;
esac

unbound_control_reload "${ucReload}"

exit
