#!/bin/bash
###############################################################################
#                                                                             #
#  IPFire.org - A linux based firewall                                        #
#  Copyright (C) 2024  IPFire Team  <info@ipfire.org>                         #
#                                                                             #
#  This program is free software: you can redistribute it and/or modify       #
#  it under the terms of the GNU General Public License as published by       #
#  the Free Software Foundation, either version 3 of the License, or          #
#  (at your option) any later version.                                        #
#                                                                             #
#  This program is distributed in the hope that it will be useful,            #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of             #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              #
#  GNU General Public License for more details.                               #
#                                                                             #
#  You should have received a copy of the GNU General Public License          #
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.      #
#                                                                             #
###############################################################################

version="2024-09-14 - v22"

###############       Main        ###############

weeks="2"                   #   default to two message logs
sortBy="name"               #   default "by name"
rpzActive="enabled"         #   default "enabled only"

while [[ $# -gt 0 ]] ; do
    case "$1" in
        --by-names | --by-name )    sortBy="name"   ;;

        --by-hits | --by-hit )      sortBy="hit"    ;;

        --by-lines | --by-line )    sortBy="line"   ;;

        --by-effect )				sortBy="effect"   ;;

        --enabled-only )            rpzActive="enabled" ;;

        --active-all )              rpzActive="all"     ;;

        [0-9] | [0-9][0-9] )        weeks=$1        ;;
    esac
    shift       # Shift after checking all the cases to get next option
done

#  get the list of message logs for N weeks
messageLogs=$( find /var/log/messages* -type f | sort --version-sort |
    head -"${weeks}" )

#  get the list of RPZ names & counts from the message log(s)
rpzNameCount=$( for logf in ${messageLogs} ; do
    zgrep --text --extended-regexp 'info: rpz: applied.* A IN$' "${logf}" |
      awk '$10 ~ /\[\w*]/ { print $10 }' ;
    done | sort | uniq --count )

#  flip results and remove brackets `[` and `]`
rpzNameCount=$( echo "${rpzNameCount}" |
    awk '{ print $2, $1 }' |
    sed --regexp-extended 's|^\[(.*)\]|\1|' )

#  grab only names
rpzNames=$( echo "${rpzNameCount}" | awk '{ print $1 }' )

#  get list of RPZ files
rpzFileList=$( find /etc/unbound/zonefiles -type f -iname "*.rpz" )

#  get basename of those files
rpzBaseNames=$( echo "${rpzFileList}" |
    sed 's|/etc/unbound/zonefiles/||g ; s|\.rpz||g ;' )

#  add to rpzNames
rpzNames="${rpzNames}"$'\n'"${rpzBaseNames}"

#  drop duplicate names
rpzNames=$( echo "${rpzNames}" | sort --unique  )

#  get line count for each RPZ
lineCount=$( echo "${rpzFileList}" | xargs wc -l )

#  get comment line count and blank line count for each RPZ
commentCount=$( echo "${rpzFileList}" | xargs grep --count -e "^$" -e "^;" )

#  get modified date each RPZ
modDateList=$( echo "${rpzFileList}" | xargs stat -c '%.10y  %n' )

ucListAuthZones=$( unbound-control list_auth_zones )

#  get width of RPZ names
pWidth=$( echo "${rpzNames}" | awk '{ print $1"   " }' | wc -L )
pFormat="%-${pWidth}s %-8s %-8s %-8s %10s %12s\n"

#  print title line
printf "${pFormat}" "name" "hits" "active" "lines" "hits/line%" "last update"
printf -- "--------------"

theResults=""
totalLines=0
totalHits=0
while read -r theName
do
    printf -- "-"        #   pretend progress bar

    #  is this RPZ list active?
    theActive="disabled"
    if grep --quiet "^${theName}\.rpz" <<< "${ucListAuthZones}"
    then
        theActive="enabled"
    else
        [[ "${rpzActive}" == enabled ]] && continue
    fi

    #  get hit count
    theHits="0"
    if output=$( grep "^${theName}\s" <<< "${rpzNameCount}" ) ; then
        theHits=$( echo "${output}" | awk '{ print $2 }' )
        totalHits=$(( totalHits + theHits ))
    fi

    #  get line count
    theLines="n/a"
    hitsPerLine="0"
    if output=$( grep --fixed-strings "/${theName}.rpz" <<< "${lineCount}" ) ; then
        theLines=$( echo "${output}" | awk '{ print $1 }' )
        totalLines=$(( totalLines + theLines ))

        if [[ "${theLines}" -gt 2 ]] ; then
            hitsPerLine=$(( 100 * theHits / theLines ))
        fi
    fi

    #  get modification date
    theModDate="n/a"
    if output=$( grep --fixed-strings "/${theName}.rpz" <<< "${modDateList}" ) ; then
        theModDate=$( echo "${output}" | awk '{ print $1 }' )
    fi

    #  add to results list
    theResults+="${theName} ${theHits} ${theActive} ${theLines} ${hitsPerLine} ${theModDate}"$'\n'

done <<< "${rpzNames}"

case "${sortBy}" in
    #  sort by "active" then by "name"
    name) sortArg=(-k3,3r -k1,1)			;;

    #  sort by "active" then by "hits" then by "name"
    hit)  sortArg=(-k3,3r -k2,2nr -k1,1)	;;

    #  sort by "active" then by "lines" then by "name"
    line) sortArg=(-k3,3r -k4,4nr -k1,1)	;;

    #  sort by "active" then by "effect" then by "name"
    effect) sortArg=(-k3,3r -k5,5nr -k1,1)	;;
esac

printf -- "--------------\n"
#  remove blank lines, sort, print as columns
echo "${theResults}" |
    awk '!/^[[:space:]]*$/' |
    sort "${sortArg[@]}"    |
    awk --assign=width="${pWidth}" \
        '{ printf "%-*s %-8s %-8s %-8s %10s %12s\n", width, $1, $2, $3, $4, $5, $6 }'

printf "${pFormat}" "" "=======" "" "========" "" ""
printf "${pFormat}" "Totals -->" "${totalHits}" "" "${totalLines}" "" ""

exit
