#!/bin/bash
###############################################################################
#                                                                             #
#  IPFire.org - A linux based firewall                                        #
#  Copyright (C) 2024  IPFire Team  <info@ipfire.org>                         #
#                                                                             #
#  This program is free software: you can redistribute it and/or modify       #
#  it under the terms of the GNU General Public License as published by       #
#  the Free Software Foundation, either version 3 of the License, or          #
#  (at your option) any later version.                                        #
#                                                                             #
#  This program is distributed in the hope that it will be useful,            #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of             #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              #
#  GNU General Public License for more details.                               #
#                                                                             #
#  You should have received a copy of the GNU General Public License          #
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.      #
#                                                                             #
###############################################################################

version="2024-12-19 - v43"

###############     Functions     ###############

source /usr/sbin/rpz-functions

###############       Main        ################

tagName="unbound"

rpzAction="${1}"                    #  input RPZ action
rpzName="${2}"                      #  input RPZ name
rpzURL="${3}"                       #  input RPZ URL
rpzOption1="${4}"                   #  input RPZ option #1
rpzOption2="${5}"                   #  input RPZ option #2

rpzConfig="/etc/unbound/local.d/${rpzName}.rpz.conf"    #  output zone conf file
rpzFile="/etc/unbound/zonefiles/${rpzName}.rpz"         #  output for RPZ file

rpzLog="yes"                        #  log default is yes
ucReload="no"                       #  reload default is no
checkConf="no"                      #  check config default is no

while [[ $# -gt 0 ]] ; do
    case "$1" in
        --no-log )      rpzLog="no"    ;;
        --no-reload )   ucReload="no"  ; checkConf="no" ;;
        --reload )      ucReload="yes" ; checkConf="yes" ;;
    esac
    shift       # Shift after checking all the cases to get next option
done

case "${rpzAction}" in
    #  add new rpz list
    add )
        check_name "${rpzName}"             #  is this a valid name?
        #  does this config already exist?  If yes, then exit
        if [[ -f "${rpzConfig}" ]] ; then
            msg_log "error: rpz: duplicate - ${rpzConfig} already exists. exit"
            exit 104
        fi

        #  is this a valid URL?
        regex='^https://[-[:alnum:]\+&@#/%?=~_|!:,.;]*[-[:alnum:]\+&@#/%=~_|]'
        if ! [[ "${rpzURL}" =~ $regex ]] ; then
            msg_log "error: rpz: the URL is not valid: \"${rpzURL}\". exit."
            exit 105
        fi

        #  create the zone config file
echo "rpz:
    name:                   ${rpzName}.rpz
    zonefile:               ${rpzFile}
    url:                    ${rpzURL}
    rpz-action-override:    nxdomain
    rpz-log:                ${rpzLog}
    rpz-log-name:           ${rpzName}
    rpz-signal-nxdomain-ra: yes" > "${rpzConfig}"

        #  set-up zonefile
        #    create an empty rpz file if it does not exist
        if [[ ! -f "${rpzFile}" ]] ; then
            touch "${rpzFile}"
            #  unbound requires these settings for rpz files
            set_permissions "${rpzFile}" "${rpzConfig}"
        fi
        ;;

    #  trash config file & rpz file
    remove )
        if ! [[ -f "${rpzConfig}" ]] ; then
            msg_log "error: rpz: cannot remove ${rpzConfig}, does not exist. exit"
            exit 106
        fi

        msg_log "info: rpz: remove config file & rpz file \"${rpzName}\""
        rm "${rpzConfig}"
        rm "${rpzFile}"
        ;;

    reload )
        check_unbound_conf "${checkConf}"
        ;;

    list )
        awk -F':' '/^\s*name:/{ gsub(/[[:blank:]]|\.rpz/, "",$2) ; NAME=$2 } \
            /^\s*url:/{ gsub(/[[:blank:]]/, "") ; print NAME"="$2":"$3} '  \
            /etc/unbound/local.d/*rpz.conf

        exit
        ;;

    unbound-restart )
        check_unbound_conf "${checkConf}"
        unbound_restart
        exit
        ;;

    * )
        msg_log "error: rpz: missing or incorrect parameter"
        printf "Usage:   $(basename "$0") <ACTION> <NAME> <URL> <OPTION> <OPTION>\n"
        printf "Version: ${version}\n"
        exit 108
        ;;

esac

unbound_control_reload "${ucReload}"

exit
