#  Added for Response Policy Zone (RPZ)
%tr = (%tr,
'rpz' => 'Response Policy Zone (RPZ)',
'rpz domain' => 'Domain',
'rpz ip statistics' => 'IP-Statistiken',
'rpz ip address' => 'IP-Adresse',
'rpz list' => 'RPZ Listen',
'rpz number of blocked domains' => 'Anzahl der blockierten Domains',
'rpz number of requests' => 'Anzahl der blockierten Anfragen',
'rpz total number of blocked requests' => 'Gesamt Anzahl der blockierten Anfragen',
'rpz percentage' => 'Prozentsatz',
'rpz statistics' => 'RPZ Statistiken',
'rpz top 10 blocked domains' => 'Top 10 geblockte Domains',
'rpz top 10 client ips' => 'Top 10 Client IPs',
'rpz total blocked bytes' => 'Bytes geblockt',
'rpz total number of blocked requests' => 'Gesamtanzahl der blockierten Anfragen',
'rpz unbound logs' => 'RPZ-Protokoll',
);
