server:
	module-config: "respip validator iterator"

rpz:
    name:					allow.rpz
    zonefile:				/etc/unbound/zonefiles/allow.rpz
    rpz-action-override:	passthru
    rpz-log:				yes
    rpz-log-name:			allow
    rpz-signal-nxdomain-ra:	yes

rpz:
    name:					block.rpz
    zonefile:				/etc/unbound/zonefiles/block.rpz
    rpz-action-override:	nxdomain
    rpz-log:				yes
    rpz-log-name:			block
    rpz-signal-nxdomain-ra:	yes
