#!/bin/bash
###############################################################################
#                                                                             #
#  IPFire.org - A linux based firewall                                        #
#  Copyright (C) 2024  IPFire Team  <info@ipfire.org>                         #
#                                                                             #
#  This program is free software: you can redistribute it and/or modify       #
#  it under the terms of the GNU General Public License as published by       #
#  the Free Software Foundation, either version 3 of the License, or          #
#  (at your option) any later version.                                        #
#                                                                             #
#  This program is distributed in the hope that it will be useful,            #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of             #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              #
#  GNU General Public License for more details.                               #
#                                                                             #
#  You should have received a copy of the GNU General Public License          #
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.      #
#                                                                             #
###############################################################################

#	v03 on 2024-07-04

###############     Functions     ###############

#	send message to message log
msg_log () {
	if /usr/bin/tty --silent ; then
		echo "${tagName}:" "$*"
	else
		/usr/bin/logger --tag "${tagName}" "$*"
	fi
}

###############       Main        ###############

tagName="unbound"

sleepTime="${1:-5m}"			#	default to sleep for 5m (5 minutes)

zoneList=$( /usr/sbin/unbound-control list_auth_zones | /usr/bin/awk '{print $1}' )

for zone in ${zoneList} ; do 
	/usr/bin/printf "disable ${zone}\t"
	/usr/sbin/unbound-control rpz_disable "${zone}"
done 

msg_log "info: rpz: disabled all zones for ${sleepTime}"

/bin/sleep "${sleepTime}"

for zone in ${zoneList} ; do 
	/usr/bin/printf "enable ${zone}\t"
	/usr/sbin/unbound-control rpz_enable "${zone}"
done

msg_log "info: rpz: enabled all zones"

exit
